### ISSUE TITLE
will not activate

### ISSUE THREAD

**Issue by CoatesIT** [matatirosolutions/filemaker-data-api-wordpress#2]
Using WordPress 5.2.4 I get the following error....
Fatal error: Uncaught TypeError: Argument 1 passed to FMDataAPI\FileMakerDataAPI::__construct() must be an instance of FMDataAPI\Settings, null given, called in /home/sites/4a/d/d99bc9231c/public_html/wp-content/plugins/filemaker-data-api-wordpress-master/src/Plugin.php on line 24 and defined in /home/sites/4a/d/d99bc9231c/public_html/wp-content/plugins/filemaker-data-api-wordpress-master/src/FileMakerDataAPI.php:30 Stack trace: #0 /home/sites/4a/d/d99bc9231c/public_html/wp-content/plugins/filemaker-data-api-wordpress-master/src/Plugin.php(24): FMDataAPI\FileMakerDataAPI->__construct(NULL) #1 /home/sites/4a/d/d99bc9231c/public_html/wp-content/plugins/filemaker-data-api-wordpress-master/fm-dataapi.php(27): FMDataAPI\Plugin->__construct() #2 /home/sites/4a/d/d99bc9231c/public_html/wp-admin/includes/plugin.php(2141): include('/home/sites/4a/...') #3 /home/sites/4a/d/d99bc9231c/public_html/wp-admin/plugins.php(175): plugin_sandbox_scrape('filemaker-data-...') #4 {main} thrown in /home/sites/4a/d/d99bc9231c/public_html/wp-content/plugins/filemaker-data-api-wordpress-master/src/FileMakerDataAPI.php on line 30

anyone got any ideas.....? thanks!

**Comment by ScottChampagne** [comment]
I just received the same error on WordPress 5.3

**Comment by steveWinter** [comment]
Apologies - in the process of addressing another request I inadvertently omitted a default value for a new setting - everything was fine if parameters existed in your database but not on first install. Please update to the current master version.
